package fr.limos.db.entities;
// default package
// Generated 5 janv. 2016 13:26:43 by Hibernate Tools 4.3.1.Final

/**
 * Answer generated by hbm2java
 */

public class Answer implements java.io.Serializable {

    private int id_answer;
    private int orderanswer;
    private int metricforagreg;
    private int fk_id_agregation;
    private int fk_id_questionforagre;
    private int fk_id_survey;
    private int fk_id_section;
    private int fk_id_question;
    private int fk_id_label;

    public Answer() {
    }

    public int getId() {
        return id_answer;
    }

    public void setId_answer(int id_answer) {
        this.id_answer = id_answer;
    }

    public int getOrderanswer() {
        return orderanswer;
    }

    public void setOrderanswer(int orderanswer) {
        this.orderanswer = orderanswer;
    }

    public int getMetricforagreg() {
        return metricforagreg;
    }

    public void setMetricforagreg(int metricforagreg) {
        this.metricforagreg = metricforagreg;
    }

    public int getFk_id_agregation() {
        return fk_id_agregation;
    }

    public void setFk_id_agregation(int fk_id_agregation) {
        this.fk_id_agregation = fk_id_agregation;
    }

    public int getFk_id_questionforagre() {
        return fk_id_questionforagre;
    }

    public void setFk_id_questionforagre(int fk_id_questionforagre) {
        this.fk_id_questionforagre = fk_id_questionforagre;
    }

    public int getid_survey() {
        return fk_id_survey;
    }

    public void setFk_id_survey(int fk_id_survey) {
        this.fk_id_survey = fk_id_survey;
    }

    public int getid_section() {
        return fk_id_section;
    }

    public void setFk_id_section(int fk_id_section) {
        this.fk_id_section = fk_id_section;
    }

    public int getid_question() {
        return fk_id_question;
    }

    public void setFk_id_question(int fk_id_question) {
        this.fk_id_question = fk_id_question;
    }

    public int getLabel() {
        return fk_id_label;
    }

    public void setFk_id_label(int fk_id_label) {
        this.fk_id_label = fk_id_label;
    }
}