package fr.limos.db.entities;
// default package
// Generated 5 janv. 2016 13:26:43 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InvestigateId generated by hbm2java
 */
@Embeddable
public class InvestigateId implements java.io.Serializable {

	private int fkIdSurvey;
	private int fkIdMedicalstaff;

	public InvestigateId() {
	}

	public InvestigateId(int fkIdSurvey, int fkIdMedicalstaff) {
		this.fkIdSurvey = fkIdSurvey;
		this.fkIdMedicalstaff = fkIdMedicalstaff;
	}

	@Column(name = "fk_id_survey", nullable = false)
	public int getFkIdSurvey() {
		return this.fkIdSurvey;
	}

	public void setFkIdSurvey(int fkIdSurvey) {
		this.fkIdSurvey = fkIdSurvey;
	}

	@Column(name = "fk_id_medicalstaff", nullable = false)
	public int getFkIdMedicalstaff() {
		return this.fkIdMedicalstaff;
	}

	public void setFkIdMedicalstaff(int fkIdMedicalstaff) {
		this.fkIdMedicalstaff = fkIdMedicalstaff;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InvestigateId))
			return false;
		InvestigateId castOther = (InvestigateId) other;

		return (this.getFkIdSurvey() == castOther.getFkIdSurvey())
				&& (this.getFkIdMedicalstaff() == castOther.getFkIdMedicalstaff());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getFkIdSurvey();
		result = 37 * result + this.getFkIdMedicalstaff();
		return result;
	}

}
