package fr.limos.db.entities;
// default package
// Generated 5 janv. 2016 13:26:43 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Investigate generated by hbm2java
 */
@Entity
@Table(name = "investigate", catalog = "chu")
public class Investigate implements java.io.Serializable {

	private InvestigateId id;
	private Survey survey;

	public Investigate() {
	}

	public Investigate(InvestigateId id, Survey survey) {
		this.id = id;
		this.survey = survey;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "fkIdSurvey", column = @Column(name = "fk_id_survey", nullable = false) ),
			@AttributeOverride(name = "fkIdMedicalstaff", column = @Column(name = "fk_id_medicalstaff", nullable = false) ) })
	public InvestigateId getId() {
		return this.id;
	}

	public void setId(InvestigateId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "fk_id_survey", nullable = false, insertable = false, updatable = false)
	public Survey getSurvey() {
		return this.survey;
	}

	public void setSurvey(Survey survey) {
		this.survey = survey;
	}

}
