package fr.limos.db.entities;
// default package
// Generated 5 janv. 2016 13:26:43 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Normalsection generated by hbm2java
 */
@Entity
@Table(name = "normalsection", catalog = "chu")
@NamedQuery(name="allnormalsection",query="SELECT i FROM Normalsection i")
public class Normalsection implements java.io.Serializable {

	private NormalsectionId id;
	private Section section;
	private Set<Question> questions = new HashSet(0);

	public Normalsection() {
	}

	public Normalsection(Section section) {
		this.section = section;
	}

	public Normalsection(Section section, Set<Question> questions) {
		this.section = section;
		this.questions = questions;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idSection", column = @Column(name = "id_section", nullable = false) ),
			@AttributeOverride(name = "fkIdSurvey", column = @Column(name = "fk_id_survey", nullable = false) ) })
	public NormalsectionId getId() {
		return this.id;
	}

	public void setId(NormalsectionId id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Section getSection() {
		return this.section;
	}

	public void setSection(Section section) {
		this.section = section;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "normalsection")
	public Set<Question> getQuestions() {
		return this.questions;
	}

	public void setQuestions(Set<Question> questions) {
		this.questions = questions;
	}

}
