package fr.limos.db.entities;
// default package
// Generated 5 janv. 2016 13:26:43 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OntolinkId generated by hbm2java
 */
@Embeddable
public class OntolinkId implements java.io.Serializable {

	private int fkIdLabel;
	private int fkOntologicaltermidOntologicalterm;

	public OntolinkId() {
	}

	public OntolinkId(int fkIdLabel, int fkOntologicaltermidOntologicalterm) {
		this.fkIdLabel = fkIdLabel;
		this.fkOntologicaltermidOntologicalterm = fkOntologicaltermidOntologicalterm;
	}

	@Column(name = "fk_id_label", nullable = false)
	public int getFkIdLabel() {
		return this.fkIdLabel;
	}

	public void setFkIdLabel(int fkIdLabel) {
		this.fkIdLabel = fkIdLabel;
	}

	@Column(name = "fk_ontologicaltermid_ontologicalterm", nullable = false)
	public int getFkOntologicaltermidOntologicalterm() {
		return this.fkOntologicaltermidOntologicalterm;
	}

	public void setFkOntologicaltermidOntologicalterm(int fkOntologicaltermidOntologicalterm) {
		this.fkOntologicaltermidOntologicalterm = fkOntologicaltermidOntologicalterm;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OntolinkId))
			return false;
		OntolinkId castOther = (OntolinkId) other;

		return (this.getFkIdLabel() == castOther.getFkIdLabel())
				&& (this.getFkOntologicaltermidOntologicalterm() == castOther.getFkOntologicaltermidOntologicalterm());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getFkIdLabel();
		result = 37 * result + this.getFkOntologicaltermidOntologicalterm();
		return result;
	}

}
