package fr.limos.db.entities;
// default package
// Generated 5 janv. 2016 13:26:43 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ontolink generated by hbm2java
 */
@Entity
@Table(name = "ontolink", catalog = "chu")
public class Ontolink implements java.io.Serializable {

	private OntolinkId id;
	private Label label;

	public Ontolink() {
	}

	public Ontolink(OntolinkId id, Label label) {
		this.id = id;
		this.label = label;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "fkIdLabel", column = @Column(name = "fk_id_label", nullable = false) ),
			@AttributeOverride(name = "fkOntologicaltermidOntologicalterm", column = @Column(name = "fk_ontologicaltermid_ontologicalterm", nullable = false) ) })
	public OntolinkId getId() {
		return this.id;
	}

	public void setId(OntolinkId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_id_label", nullable = false, insertable = false, updatable = false)
	public Label getLabel() {
		return this.label;
	}

	public void setLabel(Label label) {
		this.label = label;
	}

}
