package fr.limos.db.entities;
// default package
// Generated 5 janv. 2016 13:26:43 by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Schedule generated by hbm2java
 */
@Entity
@Table(name = "schedule", catalog = "chu")
public class Schedule implements java.io.Serializable {

	private Integer idSchedule;
	private Patient patient;
	private Survey survey;
	private Date startdate;
	private Date enddate;
	private String devicestate;
	private String wearablestate;
	private String internet;
	private int version;

	public Schedule() {
	}

	public Schedule(Patient patient, Survey survey, Date startdate, Date enddate, int version) {
		this.patient = patient;
		this.survey = survey;
		this.startdate = startdate;
		this.enddate = enddate;
		this.version = version;
	}

	public Schedule(Patient patient, Survey survey, Date startdate, Date enddate, String devicestate,
			String wearablestate, String internet, int version) {
		this.patient = patient;
		this.survey = survey;
		this.startdate = startdate;
		this.enddate = enddate;
		this.devicestate = devicestate;
		this.wearablestate = wearablestate;
		this.internet = internet;
		this.version = version;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_schedule", unique = true, nullable = false)
	public Integer getIdSchedule() {
		return this.idSchedule;
	}

	public void setIdSchedule(Integer idSchedule) {
		this.idSchedule = idSchedule;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_id_patient", nullable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_id_survey", nullable = false)
	public Survey getSurvey() {
		return this.survey;
	}

	public void setSurvey(Survey survey) {
		this.survey = survey;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "startdate", nullable = false, length = 10)
	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "enddate", nullable = false, length = 10)
	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	@Column(name = "devicestate")
	public String getDevicestate() {
		return this.devicestate;
	}

	public void setDevicestate(String devicestate) {
		this.devicestate = devicestate;
	}

	@Column(name = "wearablestate")
	public String getWearablestate() {
		return this.wearablestate;
	}

	public void setWearablestate(String wearablestate) {
		this.wearablestate = wearablestate;
	}

	@Column(name = "internet")
	public String getInternet() {
		return this.internet;
	}

	public void setInternet(String internet) {
		this.internet = internet;
	}

	@Column(name = "version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

}
