package fr.limos.db.entities;
// default package
// Generated 5 janv. 2016 13:26:43 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Text generated by hbm2java
 */
@Entity
@Table(name = "text", catalog = "chu")
public class Text implements java.io.Serializable {

	private TextId id;
	private Simplequestion simplequestion;
	private int lenght;
	private Set<Result> results = new HashSet(0);

	public Text() {
	}

	public Text(Simplequestion simplequestion, int lenght) {
		this.simplequestion = simplequestion;
		this.lenght = lenght;
	}

	public Text(Simplequestion simplequestion, int lenght, Set<Result> results) {
		this.simplequestion = simplequestion;
		this.lenght = lenght;
		this.results = results;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "fkIdQuestion", column = @Column(name = "fk_id_question", nullable = false) ),
			@AttributeOverride(name = "fkIdSection", column = @Column(name = "fk_id_section", nullable = false) ),
			@AttributeOverride(name = "fkIdSurvey", column = @Column(name = "fk_id_survey", nullable = false) ) })
	public TextId getId() {
		return this.id;
	}

	public void setId(TextId id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Simplequestion getSimplequestion() {
		return this.simplequestion;
	}

	public void setSimplequestion(Simplequestion simplequestion) {
		this.simplequestion = simplequestion;
	}

	@Column(name = "lenght", nullable = false)
	public int getLenght() {
		return this.lenght;
	}

	public void setLenght(int lenght) {
		this.lenght = lenght;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "text")
	public Set<Result> getResults() {
		return this.results;
	}

	public void setResults(Set<Result> results) {
		this.results = results;
	}

}
