package fr.limos.entities;
// default package
// Generated 5 janv. 2016 13:26:43 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AgregresultId generated by hbm2java
 */
@Embeddable
public class AgregresultId implements java.io.Serializable {

	private int fkIdResult;
	private int fkIdAgregation;
	private int fkIdSection;
	private int fkIdSurvey;

	public AgregresultId() {
	}

	public AgregresultId(int fkIdResult, int fkIdAgregation, int fkIdSection, int fkIdSurvey) {
		this.fkIdResult = fkIdResult;
		this.fkIdAgregation = fkIdAgregation;
		this.fkIdSection = fkIdSection;
		this.fkIdSurvey = fkIdSurvey;
	}

	@Column(name = "fk_id_result", nullable = false)
	public int getFkIdResult() {
		return this.fkIdResult;
	}

	public void setFkIdResult(int fkIdResult) {
		this.fkIdResult = fkIdResult;
	}

	@Column(name = "fk_id_agregation", nullable = false)
	public int getFkIdAgregation() {
		return this.fkIdAgregation;
	}

	public void setFkIdAgregation(int fkIdAgregation) {
		this.fkIdAgregation = fkIdAgregation;
	}

	@Column(name = "fk_id_section", nullable = false)
	public int getFkIdSection() {
		return this.fkIdSection;
	}

	public void setFkIdSection(int fkIdSection) {
		this.fkIdSection = fkIdSection;
	}

	@Column(name = "fk_id_survey", nullable = false)
	public int getFkIdSurvey() {
		return this.fkIdSurvey;
	}

	public void setFkIdSurvey(int fkIdSurvey) {
		this.fkIdSurvey = fkIdSurvey;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AgregresultId))
			return false;
		AgregresultId castOther = (AgregresultId) other;

		return (this.getFkIdResult() == castOther.getFkIdResult())
				&& (this.getFkIdAgregation() == castOther.getFkIdAgregation())
				&& (this.getFkIdSection() == castOther.getFkIdSection())
				&& (this.getFkIdSurvey() == castOther.getFkIdSurvey());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getFkIdResult();
		result = 37 * result + this.getFkIdAgregation();
		result = 37 * result + this.getFkIdSection();
		result = 37 * result + this.getFkIdSurvey();
		return result;
	}

}
