package fr.limos.entities;
// default package
// Generated 5 janv. 2016 13:26:43 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Agregresult generated by hbm2java
 */
@Entity
@Table(name = "agregresult", catalog = "chu")
public class Agregresult implements java.io.Serializable {

	private AgregresultId id;
	private Result result;
	private int sumagreg;

	public Agregresult() {
	}

	public Agregresult(AgregresultId id, Result result, int sumagreg) {
		this.id = id;
		this.result = result;
		this.sumagreg = sumagreg;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "fkIdResult", column = @Column(name = "fk_id_result" ) ),
			@AttributeOverride(name = "fkIdAgregation", column = @Column(name = "fk_id_agregation" ) ),
			@AttributeOverride(name = "fkIdSection", column = @Column(name = "fk_id_section" ) ),
			@AttributeOverride(name = "fkIdSurvey", column = @Column(name = "fk_id_survey") ) })
	public AgregresultId getId() {
		return this.id;
	}

	public void setId(AgregresultId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_id_result", nullable = false, insertable = false, updatable = false)
	public Result getResult() {
		return this.result;
	}

	public void setResult(Result result) {
		this.result = result;
	}

	@Column(name = "sumagreg", nullable = false)
	public int getSumagreg() {
		return this.sumagreg;
	}

	public void setSumagreg(int sumagreg) {
		this.sumagreg = sumagreg;
	}

}
