package fr.limos.entities;
// default package
// Generated 5 janv. 2016 13:26:43 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Complexquestion generated by hbm2java
 */
@Entity
@Table(name = "complexquestion", catalog = "chu")
public class Complexquestion implements java.io.Serializable {

	private ComplexquestionId id;
	private Question question;
	private Simplequestion simplequestion;

	public Complexquestion() {
	}

	public Complexquestion(Question question) {
		this.question = question;
	}

	public Complexquestion(Question question, Simplequestion simplequestion) {
		this.question = question;
		this.simplequestion = simplequestion;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "fkIdSurvey", column = @Column(name = "fk_id_survey", nullable = false) ),
			@AttributeOverride(name = "fkIdSection", column = @Column(name = "fk_id_section", nullable = false) ),
			@AttributeOverride(name = "fkIdQuestion", column = @Column(name = "fk_id_question", nullable = false) ) })
	public ComplexquestionId getId() {
		return this.id;
	}

	public void setId(ComplexquestionId id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "complexquestion")
	public Simplequestion getSimplequestion() {
		return this.simplequestion;
	}

	public void setSimplequestion(Simplequestion simplequestion) {
		this.simplequestion = simplequestion;
	}

}
