package fr.limos.entities;
// default package
// Generated 5 janv. 2016 13:26:43 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Label generated by hbm2java
 */


public class Labelchu implements java.io.Serializable {

	private Integer idLabel;
	private String shortlabel;
	private String labelfr;
	private String labelen;
	private String commentfr;
	private String commenten;
	private String unitefr;
	private String uniteen;


	public Labelchu() {
	}

	public Labelchu(Integer idLabel,String shortlabel, String labelfr) {
		this.idLabel=idLabel;
		this.shortlabel = shortlabel;
		this.labelfr = labelfr;
	}

	public Labelchu(Integer idLabel, String shortlabel, String labelfr, String labelen, String commentfr, String commenten, String unitefr,String uniteen) {
		this.idLabel=idLabel;
		this.shortlabel = shortlabel;
		this.labelfr = labelfr;
		this.labelen = labelen;
		this.commentfr = commentfr;
		this.commenten = commenten;
		this.unitefr = unitefr;
		this.uniteen = uniteen;

	}


	public Integer getIdLabel() {
		return this.idLabel;
	}

	public void setIdLabel(Integer idLabel) {
		this.idLabel = idLabel;
	}

	public String getShortlabel() {
		return this.shortlabel;
	}

	public void setShortlabel(String shortlabel) {
		this.shortlabel = shortlabel;
	}


	public String getLabelfr() {
		return this.labelfr;
	}

	public void setLabelfr(String labelfr) {
		this.labelfr = labelfr;
	}

	public String getLabelen() {
		return this.labelen;
	}

	public void setLabelen(String labelen) {
		this.labelen = labelen;
	}

	public String getCommentfr() {
		return this.commentfr;
	}

	public void setCommentfr(String commentfr) {
		this.commentfr = commentfr;
	}

	public String getCommenten() {
		return this.commenten;
	}

	public void setCommenten(String commenten) {
		this.commenten = commenten;
	}

	public String getUnitefr() {
		return this.unitefr;
	}

	public void setUnitefr(String unitefr) {
		this.unitefr = unitefr;
	}

	public String getUniteen() {
		return this.uniteen;
	}

	public void setUniteen(String uniteen) {
		this.uniteen = uniteen;
	}




}
