package fr.limos.entities;
// default package
// Generated 5 janv. 2016 13:26:43 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Patient generated by hbm2java
 */
@Entity
@Table(name = "patient", catalog = "chu")
public class Patient implements java.io.Serializable {

	private Integer idPatient;
	private String firstname;
	private String lastname;
	private String codepatient;
	private Set<Result> results = new HashSet(0);
	private Set<Schedule> schedules = new HashSet(0);

	public Patient() {
	}

	public Patient(String codepatient) {
		this.codepatient = codepatient;
	}

	public Patient(String firstname, String lastname, String codepatient, Set<Result> results, Set<Schedule> schedules) {
		this.firstname = firstname;
		this.lastname = lastname;
		this.codepatient = codepatient;
		this.results = results;
		this.schedules = schedules;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_patient", unique = true, nullable = false)
	public Integer getIdPatient() {
		return this.idPatient;
	}

	public void setIdPatient(Integer idPatient) {
		this.idPatient = idPatient;
	}

	@Column(name = "firstname")
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname")
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "codepatient", nullable = false, length = 7)
	public String getCodepatient() {
		return this.codepatient;
	}

	public void setCodepatient(String codepatient) {
		this.codepatient = codepatient;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set<Result> getResults() {
		return this.results;
	}

	public void setResults(Set<Result> results) {
		this.results = results;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set<Schedule> getSchedules() {
		return this.schedules;
	}

	public void setSchedules(Set<Schedule> schedules) {
		this.schedules = schedules;
	}

}
