package fr.limos.entities;
// default package
// Generated 5 janv. 2016 13:26:43 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * QuestionforagreId generated by hbm2java
 */
@Embeddable
public class QuestionforagreId implements java.io.Serializable {

	private int idQuestionforagre;
	private int fkIdAgregation;

	public QuestionforagreId() {
	}

	public QuestionforagreId(int idQuestionforagre, int fkIdAgregation) {
		this.idQuestionforagre = idQuestionforagre;
		this.fkIdAgregation = fkIdAgregation;
	}

	@Column(name = "id_questionforagre", nullable = false)
	public int getIdQuestionforagre() {
		return this.idQuestionforagre;
	}

	public void setIdQuestionforagre(int idQuestionforagre) {
		this.idQuestionforagre = idQuestionforagre;
	}

	@Column(name = "fk_id_agregation", nullable = false)
	public int getFkIdAgregation() {
		return this.fkIdAgregation;
	}

	public void setFkIdAgregation(int fkIdAgregation) {
		this.fkIdAgregation = fkIdAgregation;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof QuestionforagreId))
			return false;
		QuestionforagreId castOther = (QuestionforagreId) other;

		return (this.getIdQuestionforagre() == castOther.getIdQuestionforagre())
				&& (this.getFkIdAgregation() == castOther.getFkIdAgregation());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdQuestionforagre();
		result = 37 * result + this.getFkIdAgregation();
		return result;
	}

}
