package fr.limos.entities;
// default package
// Generated 5 janv. 2016 13:26:43 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Ranking generated by hbm2java
 */
@Entity
@Table(name = "ranking", catalog = "chu")
public class Ranking implements java.io.Serializable {

	private RankingId id;
	private Simplequestion simplequestion;
	private float startrank;
	private float endrank;
	private boolean integervalue;
	private Set<Result> results = new HashSet(0);

	public Ranking() {
	}

	public Ranking(Simplequestion simplequestion, float startrank, float endrank, boolean integervalue) {
		this.simplequestion = simplequestion;
		this.startrank = startrank;
		this.endrank = endrank;
		this.integervalue = integervalue;
	}

	public Ranking(Simplequestion simplequestion, float startrank, float endrank, boolean integervalue, Set<Result>  results) {
		this.simplequestion = simplequestion;
		this.startrank = startrank;
		this.endrank = endrank;
		this.integervalue = integervalue;
		this.results = results;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "fkIdQuestion", column = @Column(name = "fk_id_question") ),
			@AttributeOverride(name = "fkIdSection", column = @Column(name = "fk_id_section") ),
			@AttributeOverride(name = "fkIdSurvey", column = @Column(name = "fk_id_survey") ) })
	public RankingId getId() {
		return this.id;
	}

	public void setId(RankingId id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Simplequestion getSimplequestion() {
		return this.simplequestion;
	}

	public void setSimplequestion(Simplequestion simplequestion) {
		this.simplequestion = simplequestion;
	}

	@Column(name = "startrank", nullable = false, precision = 12, scale = 0)
	public float getStartrank() {
		return this.startrank;
	}

	public void setStartrank(float startrank) {
		this.startrank = startrank;
	}

	@Column(name = "endrank", nullable = false, precision = 12, scale = 0)
	public float getEndrank() {
		return this.endrank;
	}

	public void setEndrank(float endrank) {
		this.endrank = endrank;
	}

	@Column(name = "integervalue", nullable = false)
	public boolean isIntegervalue() {
		return this.integervalue;
	}

	public void setIntegervalue(boolean integervalue) {
		this.integervalue = integervalue;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ranking")
	public Set<Result>  getResults() {
		return this.results;
	}

	public void setResults(Set<Result>  results) {
		this.results = results;
	}

}
