package fr.limos.entities;
// default package
// Generated 5 janv. 2016 13:26:43 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TextId generated by hbm2java
 */
@Embeddable
public class TextId implements java.io.Serializable {

	private int fkIdQuestion;
	private int fkIdSection;
	private int fkIdSurvey;

	public TextId() {
	}

	public TextId(int fkIdQuestion, int fkIdSection, int fkIdSurvey) {
		this.fkIdQuestion = fkIdQuestion;
		this.fkIdSection = fkIdSection;
		this.fkIdSurvey = fkIdSurvey;
	}

	@Column(name = "fk_id_question", nullable = false)
	public int getFkIdQuestion() {
		return this.fkIdQuestion;
	}

	public void setFkIdQuestion(int fkIdQuestion) {
		this.fkIdQuestion = fkIdQuestion;
	}

	@Column(name = "fk_id_section", nullable = false)
	public int getFkIdSection() {
		return this.fkIdSection;
	}

	public void setFkIdSection(int fkIdSection) {
		this.fkIdSection = fkIdSection;
	}

	@Column(name = "fk_id_survey", nullable = false)
	public int getFkIdSurvey() {
		return this.fkIdSurvey;
	}

	public void setFkIdSurvey(int fkIdSurvey) {
		this.fkIdSurvey = fkIdSurvey;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TextId))
			return false;
		TextId castOther = (TextId) other;

		return (this.getFkIdQuestion() == castOther.getFkIdQuestion())
				&& (this.getFkIdSection() == castOther.getFkIdSection())
				&& (this.getFkIdSurvey() == castOther.getFkIdSurvey());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getFkIdQuestion();
		result = 37 * result + this.getFkIdSection();
		result = 37 * result + this.getFkIdSurvey();
		return result;
	}

}
